[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PRISMA_GENERATE_DATAPROXY = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
